# config file specific for the controller
[MQTT]
broker_ip = localhost
broker_port = 1883
client_id = owl_central_controller

[GPS]
enable = True
nmea_port = 8500
boom_width = 12.0
track_save_directory = tracks